repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: no-commit-to-branch
        args: ["--branch", "main"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.2
    hooks:
      - id: mypy
        args: ["--config-file=pyproject.toml"]
        additional_dependencies:
          - "types-requests>=2.32.4"
          - "html2text>=2024.2.26"
          - "requests>=2.31.0"
          - "pytest>=9.0.2"
          - "requests-mock>=1.12.1"
