"""
CLI entry point for telegram-sendmail.

This module is the sole owner of:
- `argparse` argument parsing
- Logging infrastructure bootstrap (syslog or console)
- Top-level exception-to-exit-code mapping
- Pipeline wiring (config -> spool -> parse -> send)

It is the only module in the package that calls `sys.exit`.

Entry point
-----------
The `main` function is registered in `pyproject.toml` under
`[project.scripts]` and is invoked by the `telegram-sendmail`
executable generated by the build backend.

Exit codes
----------
- `0`  (EX_OK)       — message delivered successfully.
- `1`  (EX_ERROR)    — operational failure (parse error, Telegram API error,
                       interactive invocation, or unexpected exception).
- `75` (EX_TEMPFAIL) — transient network failure (HTTP 429 or 5xx); the
                       calling daemon should re-queue and retry.
- `78` (EX_CONFIG)   — configuration error (missing/invalid config file).
"""

from __future__ import annotations

import argparse
import logging
import logging.handlers
import sys
from collections.abc import Callable

from telegram_sendmail import __version__
from telegram_sendmail.client import _RETRY_STATUS_CODES, TelegramClient
from telegram_sendmail.config import AppConfig, ConfigLoader
from telegram_sendmail.exceptions import (
    ConfigurationError,
    ParsingError,
    SpoolError,
    TelegramAPIError,
    TelegramSendmailError,
)
from telegram_sendmail.parser import EmailParser
from telegram_sendmail.smtp import SMTPServer
from telegram_sendmail.spool import MailSpooler

logger = logging.getLogger(__name__)

# EX_TEMPFAIL is defined in OS on POSIX; hardcode the value for portability
_EX_OK = 0
_EX_ERROR = 1
_EX_TEMPFAIL = 75
_EX_CONFIG = 78

# Pipe-mode read cap matches the SMTP SIZE limit advertised in smtp.py so that
# both entry points enforce the same ceiling consistently.
_MAX_PIPE_SIZE: int = 10_485_760  # 10 MiB
_PIPE_READ_CHUNK: int = 65_536


# --------------------------------------------------------------------------
# Delivery pipeline
# --------------------------------------------------------------------------


def _deliver(
    raw_email: str,
    sender_override: str | None,
    config: AppConfig,
) -> None:
    """
    Run the full email delivery pipeline for a single message.

    Pipeline order:
    1. **Spool**  — archive the raw email. Non-fatal: a `SpoolError` is
                    logged at WARNING level and delivery continues.
    2. **Parse**  — decode MIME structure and convert body to Telegram markup.
    3. **Format** — wrap in the Telegram message envelope with truncation.
    4. **Send**   — deliver via the Telegram Bot API.

    Args:
        raw_email:       Raw RFC 2822 email string.
        sender_override: Envelope sender from `-f`/`-r` flag or SMTP
                         `MAIL FROM`. Overrides the `From` header.
        config:          Resolved `AppConfig` instance.

    Raises:
        ParsingError:     If the email body cannot be decoded.
        TelegramAPIError: If Telegram delivery fails after all retries.
    """
    spooler = MailSpooler(config)
    try:
        spooler.write(raw_email)
    except SpoolError:
        pass  # Warning already emitted by MailSpooler.write

    parser = EmailParser(config)
    parsed = parser.parse(raw_email, sender_override=sender_override)
    text = parser.format_for_telegram(parsed)

    with TelegramClient(config) as client:
        client.send(text)


def _make_smtp_handler(config: AppConfig) -> Callable[[str, str | None], None]:
    """
    Return a closure that binds `config` to `_deliver` for use as the
    `SMTPServer.on_message` callback.
    """

    def handler(raw_email: str, envelope_sender: str | None) -> None:
        _deliver(raw_email, envelope_sender, config)

    return handler


def _bounded_stdin_read() -> str:
    """
    Read up to `_MAX_PIPE_SIZE` characters from `sys.stdin` in chunks.

    Reading in fixed-size chunks prevents a single `sys.stdin.read()` call
    from loading an arbitrarily large payload into memory before any
    downstream truncation occurs. Once the accumulated size exceeds
    `_MAX_PIPE_SIZE`, the overflow is drained without buffering and a
    `WARNING` is emitted so syslog records the event; delivery continues
    with the collected portion.

    Returns:
        The email content, at most `_MAX_PIPE_SIZE` characters long.
    """
    chunks: list[str] = []
    total = 0
    oversized = False

    while True:
        chunk = sys.stdin.read(_PIPE_READ_CHUNK)
        if not chunk:
            break

        if oversized:
            # Drain without buffering so the feeding process is not blocked.
            continue

        if total + len(chunk) > _MAX_PIPE_SIZE:
            chunks.append(chunk[: _MAX_PIPE_SIZE - total])
            total = _MAX_PIPE_SIZE
            oversized = True
        else:
            chunks.append(chunk)
            total += len(chunk)

    if oversized:
        logger.warning(
            "Pipe-mode stdin exceeded %d bytes; input truncated to limit",
            _MAX_PIPE_SIZE,
        )

    return "".join(chunks)


# --------------------------------------------------------------------------
# Logging bootstrap
# --------------------------------------------------------------------------

_SYSLOG_ADDRESS = "/dev/log"
_SYSLOG_SOCKET_FALLBACK = "/var/run/syslog"


class _TokenRedactFilter(logging.Filter):
    """
    Logging filter that replaces the bot token with a safe placeholder.

    Installed on every root-logger handler after the token is known so that
    third-party loggers (`urllib3`, `requests`) cannot leak the token at
    DEBUG level.
    """

    def __init__(self, token: str) -> None:
        super().__init__()
        self._token = token
        self._placeholder = f"{token[:8]}[…REDACTED…]"

    def filter(self, record: logging.LogRecord) -> bool:
        """Redact the token from the fully formatted message."""
        formatted = record.getMessage()
        if self._token in formatted:
            record.msg = formatted.replace(self._token, self._placeholder)
            record.args = None
        return True


def _setup_logging(console: bool, debug: bool = False) -> None:
    """
    Configure the root logger before any module-level logger fires.

    In production (`console=False`) log output goes to syslog under the
    `LOG_MAIL` facility with the process identifier `telegram-sendmail`.
    In console mode (`--console` flag) log output goes to `stderr` with
    a human-readable format, which is useful for interactive debugging and
    CI environments.

    This function must be called before `ConfigLoader.load()` so that
    configuration warnings are captured by the configured handler.

    Args:
        console: Route logs to `stderr` instead of syslog.
        debug:   Set root log level to `DEBUG`; default is `INFO`.
    """
    level = logging.DEBUG if debug else logging.INFO

    if console:
        handler: logging.Handler = logging.StreamHandler(sys.stderr)
        msgfmt = "[%(levelname)s] %(name)s: %(message)s"
        handler.setFormatter(
            logging.Formatter(msgfmt, datefmt="%Y-%m-%d %H:%M:%S"),
        )
    else:
        syslog_address: str | tuple[str, int]
        for candidate in (_SYSLOG_ADDRESS, _SYSLOG_SOCKET_FALLBACK):
            try:
                syslog_address = candidate
                handler = logging.handlers.SysLogHandler(
                    address=syslog_address,
                    facility=logging.handlers.SysLogHandler.LOG_MAIL,
                )
                break
            except OSError:
                continue
        else:
            # Neither syslog socket is accessible; fall back to stderr so
            # we do not silently swallow errors.
            handler = logging.StreamHandler(sys.stderr)

        msgfmt = "telegram-sendmail[%(process)d]: %(levelname)s %(name)s: %(message)s"
        handler.setFormatter(
            logging.Formatter(msgfmt, datefmt="%Y-%m-%d %H:%M:%S"),
        )

    logging.root.setLevel(level)
    logging.root.addHandler(handler)


# --------------------------------------------------------------------------
# Argument parser
# --------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    """
    Construct the argument parser.

    Sendmail-compatible flags are accepted and honoured or silently ignored
    as documented. Positional recipient arguments (e.g.
    `sendmail root@localhost`) are consumed via `nargs='*'` and discarded
    so that system daemons calling `sendmail <recipient>` do not cause
    argument parsing to fail.
    """
    parser = argparse.ArgumentParser(
        prog="telegram-sendmail",
        description="Forward system emails to Telegram.",
        epilog="See https://github.com/theodiv/telegram-sendmail for documentation.",
        add_help=False,
    )

    # Sendmail-compatible flags
    parser.add_argument(
        "-f",
        "-r",
        dest="sender",
        metavar="ADDRESS",
        help="set the envelope sender address (overrides the From header)",
    )
    parser.add_argument(
        "-s",
        dest="subject",
        metavar="SUBJECT",
        help="set the email subject (overrides the Subject header)",
    )
    parser.add_argument(
        "-bs",
        action="store_true",
        help="run in SMTP server mode (read SMTP commands from stdin)",
    )
    parser.add_argument(
        "-t",
        action="store_true",
        help=("extract recipients from message headers (ignored)"),
    )
    parser.add_argument(
        "-i",
        "-oi",
        action="store_true",
        dest="ignore_dots",
        help="do not treat a line with only a dot as end-of-message (ignored)",
    )

    # Positional recipients consumed and discarded for drop-in compatibility.
    # System tools like cron call: sendmail -oi -t root@localhost
    parser.add_argument(
        "recipients",
        nargs="*",
        metavar="RECIPIENT",
        help="recipient addresses (ignored; all email is forwarded to Telegram chat)",
    )

    # Custom flags
    parser.add_argument(
        "--console",
        action="store_true",
        help="log to stderr instead of syslog (useful for debugging)",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="set log level to DEBUG",
    )
    parser.add_argument(
        "--help",
        action="help",
        help="display this help message and exit",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"telegram-sendmail {__version__}",
        help="output version information and exit",
    )

    return parser


# --------------------------------------------------------------------------
# Main entry point
# --------------------------------------------------------------------------


def main() -> None:
    """
    CLI entry point registered under `[project.scripts]` in `pyproject.toml`.

    Dispatches to one of three operating modes:

    - **SMTP mode** (`-bs`): runs `SMTPServer.run()` which speaks the
      SMTP protocol on `stdin`/`stdout`.
    - **Pipe mode** (stdin is not a TTY): reads a raw email from `stdin`
      and delivers it via `_deliver()`.
    - **Interactive mode** (stdin is a TTY): prints usage information and
      exits with code `1`. This is not an error condition in the strict
      sense; it just means the tool was invoked directly from a terminal.
    """
    arg_parser = _build_parser()
    args, unknown = arg_parser.parse_known_args()

    _setup_logging(console=args.console, debug=args.debug)

    if unknown:
        logger.debug("Ignoring unrecognised arguments: %s", " ".join(unknown))

    if args.recipients:
        logger.debug(
            "Recipient argument(s) received and ignored (all mail goes to "
            "configured Telegram chat_id): %s",
            ", ".join(args.recipients),
        )

    # Loading configuration must happen after logging is set up so that
    # permission warnings from ConfigLoader are captured.
    try:
        config = ConfigLoader.load()
    except ConfigurationError as exc:
        logger.error("Configuration error: %s", exc)
        sys.exit(_EX_CONFIG)

    token_filter = _TokenRedactFilter(config.token)
    for handler in logging.root.handlers:
        handler.addFilter(token_filter)

    if args.bs:
        sys.exit(_run_smtp_mode(config))
    elif not sys.stdin.isatty():
        sys.exit(_run_pipe_mode(args.sender, args.subject, config))
    else:
        sys.exit(_run_interactive_mode())


def _run_smtp_mode(config: AppConfig) -> int:
    """Launch the SMTP state machine and map exceptions to exit codes."""
    logger.info("Starting SMTP server mode")
    try:
        server = SMTPServer(config, on_message=_make_smtp_handler(config))
        server.run()
        return _EX_OK
    except KeyboardInterrupt:
        logger.info("SMTP session interrupted by user")
        return _EX_OK
    except TelegramSendmailError as exc:
        logger.error("%s", exc)
        return _EX_ERROR
    except Exception as exc:
        logger.error("Unexpected error in SMTP mode: %s", exc)
        return _EX_ERROR


def _run_pipe_mode(
    sender_override: str | None,
    subject_override: str | None,
    config: AppConfig,
) -> int:
    """Read email from stdin and deliver it; return an exit code."""
    try:
        raw_email = _bounded_stdin_read()
    except Exception as exc:
        logger.error("Failed to read email from stdin: %s", exc)
        return _EX_ERROR

    # The parser accepts sender_override; subject must be injected as a
    # synthetic header when passed via the CLI flag so that the existing
    # parser interface is not widened unnecessarily.
    #
    # RFC 2822 §2.2: field names are case-insensitive, so we must perform
    # a case-insensitive search to avoid injecting a duplicate header when
    # the original uses a non-canonical casing (e.g. "subject:" instead of
    # "Subject:").
    if subject_override and "subject:" not in raw_email[:500].lower():
        raw_email = f"Subject: {subject_override}\n{raw_email}"

    try:
        _deliver(raw_email, sender_override, config)
        return _EX_OK
    except ParsingError as exc:
        logger.error("Failed to parse email: %s", exc)
        return _EX_ERROR
    except TelegramAPIError as exc:
        status = getattr(exc, "status_code", None)
        if status is not None and status in _RETRY_STATUS_CODES:
            # Transient HTTP failure: signal the caller to retry later.
            logger.warning(
                "Telegram API transient failure (HTTP %d); signalling EX_TEMPFAIL",
                status,
            )
            return _EX_TEMPFAIL
        logger.error("Telegram delivery failed: %s", exc)
        return _EX_ERROR
    except TelegramSendmailError as exc:
        logger.error("%s", exc)
        return _EX_ERROR
    except Exception as exc:
        logger.error("Unexpected error in pipe mode: %s", exc)
        return _EX_ERROR


def _run_interactive_mode() -> int:
    """
    Emit a helpful message when the tool is invoked directly from a terminal.

    This is not a hard error, but the tool is not designed for interactive
    use. Returns exit code 1 to signal to the shell that nothing was
    delivered.
    """
    print(
        f"telegram-sendmail {__version__}\n"
        "\n"
        "This tool is designed to be invoked by system daemons as a sendmail\n"
        "replacement, not run interactively from a terminal.\n"
        "\n"
        "Pipe mode:  echo 'Subject: Test\\n\\nHello' | telegram-sendmail\n"
        "SMTP mode:  telegram-sendmail -bs\n"
        "Debug mode: echo 'test' | telegram-sendmail --console --debug\n"
        "\n"
        "For full documentation: telegram-sendmail --help",
        file=sys.stderr,
    )
    return _EX_ERROR


if __name__ == "__main__":
    main()
